### PR TITLE
Updated NeRF to work in latent space

### PR DESCRIPTION
**Pull request by eladrich**

### CODE REVIEW

**Comment by samedii** [comment]
Did you get this to work?

**Comment by eladrich** [comment]
Oops, didn't mean to open a pull request yet, as my fork doesn't support both modes 

The latent mode does seem to work correctly if anyone wants to give it a try
Left: original, right: latent
ezgif-3-f0e750a8fa

So far it looks to me like it converges faster, but isn't able to capture fine details

**Comment by samedii** [comment]
Thanks! Sounds very cool :D

**Comment by ashawkey** [comment]
Wow, this is really interesting! Thanks for the information, I'll have a try too.

**Pull request closed without merging**
