### PR TITLE
add images to tensorboard, add --name to compare data in tensorboard

### PR DESCRIPTION
**Pull request by flobotics**
adding images to tensorboard to have nice viewing.

adding --name to run the same project (--text) with different settings (--fp16, --jitter_pose, etc)  .  E.g. run with --name "cuda_ray,fp16,seed=100"  and the next run with --name "cuda_ray,seed=400"  . In tensorboard you can nicely compare then the runs.

Run inside the project dir on cmdline:   tensorboard --logdir .

tensorboard

tensorboard1

### CODE REVIEW

**Comment by ashawkey** [comment]
Thanks for your efforts! However, this is a fairly large change to the current logging design, and there are several issues:
1. `if tensorbardX:` is always true, and it should be `if self.use_tensorboardX:` for consistency.
2. Currently we already write all validation images directly to the disk, so writing it again to tensorboard is somewhat duplicated. It's better to disable logging to disk if we `use_tensorboardX`, although personally I prefer logging to disk and may set that to default...
3. I recommend not to use another `opt.name`, and always put the name to `opt.workspace`, like `--workspace trial_elephant1`. To compare against multiple runs, you could use `tensorboard --logdir=name1:/path/to/logs/1,name2:/path/to/logs/2`.

Again, thanks for your contributions, but currently I cannot merge it directly.

**Comment by flobotics** [comment]
would it be ok, to implement e.g.  --enable-disk-logging  --enable-tensorboard-logging  . Default is disk-logging, and tensorboard-logging is DISABLED default.   If tensorboard-logging is enabled, it logs all tensorboard values ?

So you could enable/disable both like you wish.

the --name could be  --run_name  .


If you use tensorboard --logdir=name1:/path/to/logs/1,name2:/path/to/logs/2   you need to watch into the log-files to see what cmdline you used, and then add it to the tensorboard call everytime.  Also you need to restart everytime tensorboard with new names, when you do the next run.

what do you think?

**Comment by ashawkey** [comment]
I really appreciate your work, and it's reasonable if you are doing lots of experiments for comparison. But I still want to keep this codebase simple for now, e.g., users don't need to know the difference between `run_name` and `workspace`, and there is only one way to achieve a goal, so we don't get lost in training framework details.
BTW, you could try to run tensorboard directly at the parent directory of all `trial_` folders so it automatically find all log files with names, and add the run_name to workspace, like `trail_elephant_xxxx`.

**Comment by flobotics** [comment]
ok, keeping codebase simple is a very good reason i understand

thx

**Comment by ashawkey** [comment]
Thanks for the understanding!

**Pull request closed without merging**
