### PR TITLE
[taichi] Fix missing volume render test

### PR DESCRIPTION
**Pull request by erizmr**
Fix missing `volume_render_test.py` and update the deprecated annotation.

### CODE REVIEW

**Comment by erizmr** [comment]
Hi @ashawkey , it will be great appreciated if you can help review. Thanks!

**Comment by ashawkey** [comment]
Thanks!

**Comment by erizmr** [comment]
Hi @r530044129 , thanks for reporting this. Please refer to the fix PR #178.

**Comment by r530044129** [comment]
thanks, it's work. I get the validation pngs.
But when i finish training, i want to export the obj mesh, there is another problem
It's seems that there is no mesh or somehing?
image

**Comment by erizmr** [comment]
Hi @r530044129 , happy to hear that it works. The `save_mesh` has not been tested for the Taichi backend. According to the log info you provided, I think there are internal variables name mismatches between Taichi encoder and post-processing pipeline. I would like to file an issue and try to make it compatible.

**Pull request merged**
