### PR TITLE
Part of reproduction of the paper - R-precision

### PR DESCRIPTION
**Pull request by Justinfungi**
Thank you so much for the reproduction of dream fusion. it is a very decent job!

I would like to help to improve the repo. Currently, I have added new functionality to test the CLIP precision which the original paper used to compare with other benchmarks. Hopefully, It can help to improve the completeness of this repo and make this become more fascinating.

I will try to keep on helping improve this repo. 

2 changes:
1: a py file added
2. readme add evaluation part

### CODE REVIEW

**Comment by ashawkey** [comment]
@Justinfungi Hi, Thanks for your contribution! Are the current commits ready or not?

**Comment by Justinfungi** [comment]
> @Justinfungi Hi, Thanks for your contribution! Are the current commits ready or not?

Yup, you could merge it first for the precision part. i think it is done. 

Also, I have another idea going on. When I finish I will try to pull it to see see

**Comment by Justinfungi** [comment]
> > @Justinfungi Hi, Thanks for your contribution! Are the current commits ready or not?
> 
> @ashawkey Yup, you could merge it first for the precision part. i think it is done.
> 
> Also, I have another idea going on. When I finish I will try to pull it to see see

**Comment by Justinfungi** [comment]
image
Only these 4 for the R-precision

**Pull request closed without merging**
